spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot-jpa?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: ngl143252
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048


  thymeleaf:
    cache: false
    cache-period: 0
    mode: LEGACYHTML5
  template:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true